import React from 'react';
import {
  Card,
  CardContent,
  Typography,
  Stack,
  Switch,
  Box,
  Divider,
} from '@mui/material';
import type { UserSettings } from '../types/settings.types';

interface GeneralSettingsProps {
  settings: UserSettings;
  onUpdate: <K extends keyof UserSettings>(key: K, value: UserSettings[K]) => void;
}

export const GeneralSettings: React.FC<GeneralSettingsProps> = ({
  settings,
  onUpdate,
}) => {
  return (
    <Card
      elevation={0}
      sx={{
        borderRadius: '16px',
        border: '1px solid',
        borderColor: 'divider',
        bgcolor: 'background.paper',
      }}
    >
      <CardContent sx={{ p: { xs: 2, sm: 3 } }}>
        <Typography variant="h6" sx={{ fontWeight: 700, fontSize: { xs: '1.05rem', sm: '1.25rem' } }} gutterBottom>
          General & Interaction Preferences
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2.5, fontSize: { xs: '0.82rem', sm: '0.875rem' } }}>
          Manage stream rendering behavior, keyboard shortcuts, and memory features.
        </Typography>

        <Stack spacing={2}>
          <Box sx={{ display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 2 }}>
            <Box sx={{ minWidth: 0, flex: 1 }}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: { xs: '0.85rem', sm: '0.875rem' } }}>
                Real-Time Streaming
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ fontSize: { xs: '0.78rem', sm: '0.85rem' } }}>
                Stream words as they are generated by the neural network for instant reading.
              </Typography>
            </Box>
            <Switch
              checked={settings.streamResponses}
              onChange={(e) => onUpdate('streamResponses', e.target.checked)}
              sx={{ flexShrink: 0 }}
            />
          </Box>

          <Divider />

          <Box sx={{ display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 2 }}>
            <Box sx={{ minWidth: 0, flex: 1 }}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: { xs: '0.85rem', sm: '0.875rem' } }}>
                Persistent Workspace Memory
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ fontSize: { xs: '0.78rem', sm: '0.85rem' } }}>
                Allow AT AI to remember your technical stack preferences across conversations.
              </Typography>
            </Box>
            <Switch
              checked={settings.enableMemory}
              onChange={(e) => onUpdate('enableMemory', e.target.checked)}
              sx={{ flexShrink: 0 }}
            />
          </Box>

          <Divider />

          <Box sx={{ display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 2 }}>
            <Box sx={{ minWidth: 0, flex: 1 }}>
              <Typography variant="subtitle2" sx={{ fontWeight: 600, fontSize: { xs: '0.85rem', sm: '0.875rem' } }}>
                Send with Enter Key
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ fontSize: { xs: '0.78rem', sm: '0.85rem' } }}>
                Press Enter to send message, Shift + Enter for a new line.
              </Typography>
            </Box>
            <Switch
              checked={settings.sendOnEnter}
              onChange={(e) => onUpdate('sendOnEnter', e.target.checked)}
              sx={{ flexShrink: 0 }}
            />
          </Box>
        </Stack>
      </CardContent>
    </Card>
  );
};
